name: Publish Advent of Code Statistics to Personal Slack

on:
  schedule:
    # 10pm Central time, December 1-30
    - cron:  '0 4 2-31 12 *'
    # 10pm Central time, December 31 & January 1
    - cron:  '0 4 1-2 1 *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies with poetry
        run: poetry install --no-interaction --no-dev --extras leaderboard

      - name: Run Python script
        run: |
          poetry run python .github/leaderboard.py
        env:
          LEADERBOARD_ID: ${{ secrets.LEADERBOARD_ID }}
          SESSION_ID: ${{ secrets.SESSION_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
